require 'asset_manager/active_record'
require 'asset_manager/deprecated.rb'
require 'asset_manager/custom_versions.rb'
require 'asset_manager/touch_translation.rb'
require 'asset_manager/translations.rb'
